Repository shibayan/Sharprompt, pull requests merged in 2019-08, with the labels that each got.

#10 Fixed buffer boundary error
  Example/Program.cs
  Sharprompt/Confirm.cs
  Sharprompt/ConsoleRenderer.cs
  Sharprompt/ConsoleScope.cs
  Sharprompt/Input.cs
  Sharprompt/Password.cs
Labels: bug

#11 Avoid common keywords
  Sharprompt/Confirm.cs
  Sharprompt/ConsoleScope.cs
  Sharprompt/Error.cs
  Sharprompt/Input.cs
  Sharprompt/Password.cs
  Sharprompt/Prompt.cs
  Sharprompt/Select.cs
  Sharprompt/Validators.cs
Labels: enhancement

#12 Update README.md for 1.0.0-preview2
  README.md
Labels: documentation

#14 Fixed small typo
  Sharprompt/Sharprompt.csproj
Labels: bug

#17 Fixed nullable value handling
  Sharprompt/Input.cs
  Sharprompt/ValidationError.cs
Labels: bug

#16 Adding Select filtering
  Sharprompt/Prompt.cs
  Sharprompt/Select.cs
Labels: enhancement

#19 Adding macOS support
  README.md
Labels: documentation

#20 Adding template rendering models
  Sharprompt/Confirm.cs
  Sharprompt/ConsoleScope.cs
  Sharprompt/Input.cs
  Sharprompt/Password.cs
  Sharprompt/Prompt.cs
  Sharprompt/Select.cs
Labels: enhancement

#22 Fixed incorrect cursor location
  Sharprompt/ConsoleRenderer.cs
  Sharprompt/ConsoleScope.cs
Labels: bug

#23 Update README.md for v1.0.0
  README.md
Labels: documentation

#24 Fixed ValueType error handling
  Sharprompt/Input.cs
Labels: bug

#25 Remove version option
  README.md
Labels: documentation

#29 Added .vscode to gitignore paths.
  .gitignore
Labels: enhancement

#27 Fix selection of default values
  Sharprompt/Select.cs
Labels: bug

#32 Fixed rendering bug when handling long strings
  Sharprompt/ConsoleRenderer.cs
  Sharprompt/Select.cs
Labels: bug
