Repository shibayan/Sharprompt, pull requests merged in 2021-08, with the labels that each got.

#139 Fixed AutoForms multi-select error
  Sharprompt/Prompt.AutoForms.cs
Labels: bug

#137 Improve rendering performance
  Sharprompt/Drivers/DefaultConsoleDriver.cs
  Sharprompt/Drivers/IConsoleDriver.cs
  Sharprompt/Forms/ConfirmForm.cs
  Sharprompt/Forms/FormBase.cs
  Sharprompt/Forms/FormRenderer.cs
  Sharprompt/Forms/InputForm.cs
  Sharprompt/Forms/ListForm.cs
  Sharprompt/Forms/MultiSelectForm.cs
  Sharprompt/Forms/PasswordForm.cs
  Sharprompt/Forms/SelectForm.cs
  Sharprompt/Internal/Cursor.cs
  Sharprompt/Internal/EastAsianWidth.cs
  Sharprompt/Internal/OffscreenBuffer.cs
  Sharprompt/Internal/Paginator.cs
  Sharprompt/Internal/RenderScope.cs
  Sharprompt/Prompt.Customize.cs
Labels: enhancement

#140 Make error message color customizable
  Sharprompt/Internal/OffscreenBuffer.cs
  Sharprompt/Prompt.Customize.cs
Labels: enhancement

#141 Fixed invalid cursor position
  Sharprompt/Drivers/DefaultConsoleDriver.cs
  Sharprompt/Forms/ConfirmForm.cs
  Sharprompt/Forms/FormRenderer.cs
  Sharprompt/Forms/InputForm.cs
  Sharprompt/Forms/ListForm.cs
  Sharprompt/Forms/PasswordForm.cs
  Sharprompt/Internal/OffscreenBuffer.cs
Labels: bug

#143 Update NuGet metadata and README badge
  .github/FUNDING.yml
  README.md
  Sharprompt/Sharprompt.csproj
Labels: documentation

#145 Adding model-based and customize feature in README
  README.md
  Sharprompt/Sharprompt.csproj
Labels: documentation

#147 Add delete functionality to List prompt
  Sharprompt/Forms/ListForm.cs
Labels: enhancement

#150 Adding `ThrowExceptionOnCancel` global options
  README.md
  Sharprompt/Drivers/DefaultConsoleDriver.cs
  Sharprompt/Drivers/IConsoleDriver.cs
  Sharprompt/Forms/FormBase.cs
  Sharprompt/Forms/FormRenderer.cs
  Sharprompt/Internal/OffscreenBuffer.cs
  Sharprompt/Prompt.Customize.cs
  Sharprompt/PromptCanceledException.cs
Labels: enhancement

#148 Refactoring console render methods
  Sharprompt.Example/Program.cs
  Sharprompt/Drivers/DefaultConsoleDriver.cs
  Sharprompt/Forms/ConfirmForm.cs
  Sharprompt/Forms/FormRenderer.cs
  Sharprompt/Forms/InputForm.cs
  Sharprompt/Forms/ListForm.cs
  Sharprompt/Forms/MultiSelectForm.cs
  Sharprompt/Forms/PasswordForm.cs
  Sharprompt/Forms/SelectForm.cs
  Sharprompt/Internal/Cursor.cs
  Sharprompt/Internal/EastAsianWidth.cs
  Sharprompt/Internal/OffscreenBuffer.cs
  Sharprompt/Internal/OffscreenBufferExtensions.cs
Labels: enhancement

#152 Added a class for common processing of input text
  Sharprompt/Forms/ConfirmForm.cs
  Sharprompt/Forms/InputForm.cs
  Sharprompt/Forms/ListForm.cs
  Sharprompt/Forms/MultiSelectForm.cs
  Sharprompt/Forms/PasswordForm.cs
  Sharprompt/Forms/SelectForm.cs
  Sharprompt/Internal/TextInputBuffer.cs
Labels: enhancement

#154 Streamlined nullable type handling
  Sharprompt/Forms/ConfirmForm.cs
  Sharprompt/Forms/FormRenderer.cs
  Sharprompt/Forms/InputForm.cs
  Sharprompt/Forms/ListForm.cs
  Sharprompt/Forms/MultiSelectForm.cs
  Sharprompt/Forms/PasswordForm.cs
  Sharprompt/Internal/EnumValue.cs
  Sharprompt/Internal/OffscreenBuffer.cs
  Sharprompt/Internal/Optional.cs
  Sharprompt/Internal/TypeHelper.cs
  Sharprompt/Internal/ValidatorsExtensions.cs
  Sharprompt/Prompt.Basic.cs
  Sharprompt/Validators.cs
Labels: enhancement

#157 Change to use `TypeDescriptor.GetConverter` for type change
  Sharprompt/Internal/TypeHelper.cs
Labels: enhancement

#158 Password mask characters can now be changed
  Sharprompt.Example/Program.cs
  Sharprompt/Forms/PasswordForm.cs
  Sharprompt/PasswordOptions.cs
  Sharprompt/Prompt.AutoForms.cs
  Sharprompt/Prompt.Basic.cs
Labels: enhancement
